version: 2.1
jobs:
  build:
    docker:
        - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v9-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Setup rsync
          command: sudo apt-get -y install rsync
      - run:
          name: Remove 'r' characters from the vendor script (otherwise it won't execute)
          command: sed $'s/\r$//' ./scripts/vendor.sh > ./scripts/vendor.sh
      - run:
          name: Install Top Deps
          command: yarn install
      - run:
          name: Install Sub Packages Deps
          command: yarn test:ci
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: cache-v9-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
